### PR TITLE
[Mesh] searche boundary nodes in NodeSearch

### PR DESCRIPTION
**Pull request by norihiro-w**
As titled.

### CODE REVIEW

**Comment by chleh** [comment]
Isn't such a feature already implemented somewhere? AFAIK we need to search boundary nodes on a geometry in order to set up BCs.
What's the difference to this PR?

**Comment by norihiro-w** [comment]
there are some implementations similar to this, but are not what I need. What eventually I need is to check if a node is on domain boundary, not on a particular geometry.

**Comment by endJunction** [comment]
Please rebase to 6.0.7 before merging.

**Comment by TomFischer** [comment]
:+1:

**Pull request merged**
