### PR TITLE
ODE Solver for transient and nonlinear processes

### PR DESCRIPTION
**Pull request by chleh**
I took the last few days to take an epic attempt on reinventing the wheel. Here's the result: A new ODE solver structure. It is not yet feature-complete—like small child—but it is shiny and new, call it iSolver if you like.

I will try to finish the work on this PR until Tuesday, 16 Feb. Do not review yet (although the structures will not change anymore).

TODO:
* [x] replace present timeloop
* [x] iron out some edges with linear solvers and matrix classes (separate PR)
* [x] header guards, copyright texts
* [x] API docs (mostly done)
* [ ] Petsc matrix and vector (stub done, todo: implementation, tests)
* [x] :no_entry_sign: LIS matrix and vector: I'd like to drop them since BLAS functionality is only provided for dense matrices. Discuss.
* [ ] some cleanup
* [ ] write builders that parse configuration options
* [x] clean up BLAS interface

Also important:
* [ ] Compare test cases to actual data. Currently the tests only "run", but are not compared to analytical solutions. It would be nice if some of the mathematicians could do that comparison. Everything is prepared, only the right tolerances have to be given.

Future work:
* [ ] save some matrices (i.e. save space)
* [ ] adaptive time stepping
* [ ] different error norms
* [ ] numerical Jacobians
* [ ] process coupling
* [ ] ...

### CODE REVIEW

**Comment by chleh** [comment]
Most critical work is done. Tomorrow morning I will
* get the tests back to run
* clean up a bit
* work at the various TODOs that are scattered all across.

**Comment by chleh** [comment]
`ctest -E LARGE` with EigenLis runs for me now again.

**Comment by bilke** [comment]
Jenkins test this please!

**Comment by chleh** [comment]
Superseded by #1050.

**Pull request closed without merging**
