### PR TITLE
Update copyright years to 2012-2017.

### PR DESCRIPTION
**Pull request by endJunction**
Automatic substitution...

### CODE REVIEW

**Comment by chleh** [comment]
1277 lines changed but only 1274 files. So there must be some files with duplicate years. Is that correct? I don't want to scroll through all the files.
If OK ⏩

**Comment by endJunction** [comment]
These are coming from the output messages in 
```
> ag 'Copyright \(c\) 2012-' -c | grep -v ':1'                            
Applications/DataExplorer/DataView/LicenseDialog.cpp:2
Applications/Utils/SimpleMeshCreation/generateStructuredMesh.cpp:2
Applications/CLI/ogs.cpp:2
```

**Comment by chleh** [comment]
OK, thanks.

**Comment by bilke** [comment]
⏩

**Pull request merged**
