### PR TITLE
[Jenkins] Show Doxygen and web html reports for failing builds too

### PR DESCRIPTION
**Pull request by bilke**
If a build failed the report was not published before.

### CODE REVIEW

**Comment by bilke** [comment]
@chleh Doxygen reports were built for PRs all the time but were simply not published by Jenkins if the build failed. This fixes it.

**Comment by chleh** [comment]
Very nice. @bilke, the question that I sent you was because I just didn't find the Doxygen link in Jenkins' Blue Ocean view. Is there such a link in Blue Ocean?
Together with @TomFischer in the meantime we found out (again) that the Doxygen link exists in the classical Jenkins view, e.g., https://jenkins.opengeosys.org/job/ufz/job/ogs/view/change-requests/job/PR-1804/

Maybe it could be added to the developer guide (e.g. here https://docs.opengeosys.org/docs/devguide/testing/jenkins) that there is such a Doxygen link in Jenkins? Or is it already documented somewhere and I just didn't find it?

**Comment by chleh** [comment]
Some tests failed, but there is no Doxygen 😢 
https://jenkins.opengeosys.org/job/ufz/job/ogs/view/change-requests/job/PR-1812/Doxygen/
https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-1812/

**Comment by bilke** [comment]
Everything is green, short description in the developer guide added.

**Pull request merged**
