### PR TITLE
 	[HT]Fixed a bug in HTFEM caused by gravity term

### PR DESCRIPTION
**Pull request by wenqing**
Program will crash in HTFEM if the body force is set to zero in the project file.
<specific_body_force>0 0</specific_body_force>

This PR fixes that bug.

### CODE REVIEW

**Comment by chleh** [comment]
⏩

**Comment by TomFischer** [comment]
Thank you for discovering the bug. I would prefer a similar solution like in the ComponentTransport process. I prepared a branch in my repo https://github.com/TomFischer/ogs/tree/ht-gravity-fix for discussion.

**Comment by endJunction** [comment]
Looks good!
@wenqing and @TomFischer Please make decision which solution to take.

**Comment by wenqing** [comment]
@TomFischer  I just wrote a comment in your branch.

**Comment by wenqing** [comment]
@TomFischer  Since you wan to keep  _process_data.has_gravity for consistency in HTFEM, ComponentTransport , and  RichardsComponentTransport, I would like to close this PR. Would you please send a PR from https://github.com/TomFischer/ogs/tree/ht-gravity-fix?

**Pull request closed without merging**
