### PR TITLE
Fixes for AlgorithmProperties and get- / setValue()-removal: Utils

### PR DESCRIPTION
**Pull request by endJunction**
Extract from https://github.com/ufz/ogs/pull/897

### CODE REVIEW

**Comment by endJunction** [comment]
Jenkins, test this please.

**Comment by TomFischer** [comment]
Send you some commits via a PR.

**Comment by endJunction** [comment]
@TomFischer Suggest to make an extra PR after this is merged.

**Comment by TomFischer** [comment]
@endJunction Okay.

**Pull request merged**
