### PR TITLE
RichardsM: Add missing saturation in bulk density computation

### PR DESCRIPTION
**Pull request by ThieJan**
Richards Mechanics process
-Missing saturation in bulk density computation added

### CODE REVIEW

**Comment by nagelt** [comment]
Change is correct.

**Comment by ThieJan** [comment]
> 
> 
> 👍
> It can be merged once the related reference results are updated.

We try with reference solutions computed here or shall we use the results from the azure/ jenkins nodes as references ?

**Comment by endJunction** [comment]
Creating own references is easier, just run the ctests and overwrite the files in source/Tests/Data from build/Tests/Data/ with something like:
```sh
cd source/Tests/Data/X
for i in *_ts_*.vtu; do cp build/Tests/Data/X/${i} .; done
```
Then commit only changed files...

**Comment by endJunction** [comment]
clang-format. See some info for pre-commit hooks: https://github.com/ufz/ogs-utils/tree/master/dev/code-formatting/clang-format-pre-commit-hook

**Pull request merged**
