### PR TITLE
Fixed a compilation warning

### PR DESCRIPTION
**Pull request by wenqing**
as titled.

### CODE REVIEW

**Comment by endJunction** [comment]
It would be better, I think, to update other code to use `int` instead.
What is the warning? (I'm asking because I don't get any...)

**Comment by wenqing** [comment]
@endJunction 
due to 
``virtual unsigned getNumberOfComponents() const = 0;``
https://github.com/ufz/ogs/blob/master/ProcessLib/Parameter/Parameter.h#L70

**Comment by endJunction** [comment]
OK, I'll have a look until Friday.

**Comment by wenqing** [comment]
@endJunction Sorry, closed by mistake

**Pull request closed without merging**
