### PR TITLE
Added a member of inverse_value to MPL::Property

### PR DESCRIPTION
**Pull request by wenqing**
For capillary saturation models, the newly added member function of `inverse_value` gets capillary pressure via saturation. In the existing classes for capillary saturation models, the member function of `value` represents function of S(p_c). This is not adequate to the conventional definition of such models. Here are suggestions for future changes for  capillary pressure model classes:
```
Property::value:  Pc(S)
Property::inverse_value:  S(Pc)
```

1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.0)
2. [x] Tests covering your feature were added? Yes
3. [x] Any new feature or behavior change was documented? yes

### CODE REVIEW

**Comment by endJunction** [comment]
Not sure about the implementation of the inverse for the van Genuchten saturation. For an inverse the identity f^{-1}(f(x)) = x must hold for the whole domain of definition. But maximum capillary pressure cuts it off. Maybe it is a process' internal property?

**Comment by wenqing** [comment]
> Not sure about the implementation of the inverse for the van Genuchten saturation. For an inverse the identity f^{-1}(f(x)) = x must hold for the whole domain of definition. But maximum capillary pressure cuts it off. Maybe it is a process' internal property?

It should be a property of the water retention curve Pc(S). When S->0, Pc(S)->∞. `pc_max` can be used as a restriction for numerical stability.

**Comment by endJunction** [comment]
> It should be a property of the water retention curve Pc(S). When S->0, Pc(S)->∞. `pc_max` can be used as a restriction for numerical stability.

numerical stability of the material property or the stability of the process?

**Comment by wenqing** [comment]
> > It should be a property of the water retention curve Pc(S). When S->0, Pc(S)->∞. `pc_max` can be used as a restriction for numerical stability.
> 
> numerical stability of the material property or the stability of the process?

Like the saturation restriction, numerically it is for the stability in solving the nonlinear system, physically the capillary pressure can not be infinite. If the restriction is set in process level, meaning set a restriction in solution, it is meaningless both in physics and numerics.  

For the maximum capillary pressure restriction,  there are formulas on page 340 in Computational Methods in Environmental Fluid Mechanics by Olaf).

**Comment by endJunction** [comment]
Maybe it is better to have a different property such as `capillary_pressure`?
I'm still against a function called `inverseValue` not being an inverse.
Another thought: In RM, for example, it is possible to set saturation to a constant value (*e.g.* 1 for simple setups). For such case it is not possible to define a useful inverse relation between saturation and capillary pressure.
So for now I tend to `capillary_pressure` property. Others here might have a better ideas.

**Comment by wenqing** [comment]
> Maybe it is better to have a different property such as `capillary_pressure`?
> I'm still against a function called `inverseValue` not being an inverse.
> Another thought: In RM, for example, it is possible to set saturation to a constant value (_e.g._ 1 for simple setups). For such case it is not possible to define a useful inverse relation between saturation and capillary pressure.
> So for now I tend to `capillary_pressure` property. Others here might have better ideas.

Then I have the following idea with property type of `saturation_capillary_pressure` and `capillary_pressure_saturation`:
```
template <typename T>
class vanGenuchtenBase : public Property
{
    value()
    ....
};
 
class GenuchtenSaturationCapillaryPressure : public vanGenuchtenBase<Derived>
{
    value()
    ...
}; 
class GenuchtenCapillaryPressureSaturation : public vanGenuchtenBase<Derived>
{
    value()
    ...
};

```

**Pull request closed without merging**
