### PR TITLE
disable testing sparsity pattern in PETSc builds

### PR DESCRIPTION
**Pull request by norihiro-w**
as titled. this fixes the Jenkins error

### CODE REVIEW

**Comment by chleh** [comment]
Has Jenkins been failing for a longer time because of these tests? There haven't been any changes to the sparsity pattern code recently (#1549 not merged yet), right? Do you know why the tests fail so badly that they have to be disabled?

**Comment by norihiro-w** [comment]
it's because of #1548

**Comment by chleh** [comment]
Is it then possible to properly fix the tests in a reasonable amount of time instead of just disabling them?
Or, does it make sense to fix them, i.e. does it make sense to run the same sparsity pattern test for PETSc and non-PETSc builds?

**Comment by norihiro-w** [comment]
unfortunately not, because
- this PR fixes the sparsity pattern for the Eigen case.  The sparsity pattern PETSc requires is different. 
- PETSc builds requires passing `NodePartitionedMesh` to `MeshComponentMap`. The tests need to somehow support creating the partitioned mesh.

**Comment by chleh** [comment]
I just saw, you introduced the tests in #1548. And they fail this way:
```
testrunner: /gpfs1/data/ogs/jenkins/workspace/OGS-6/Linux-PRs-dynamic/ogs/NumLib/DOF/MeshComponentMap.cpp:68: NumLib::MeshComponentMap::MeshComponentMap(const std::__debug::vector<std::unique_ptr<MeshLib::MeshSubsets> >&, NumLib::ComponentOrder): Assertion `dynamic_cast<MeshLib::NodePartitionedMesh const*>( &mesh_subset.getMesh()) != nullptr' failed.
```

So disabling them is OK for me. :fast_forward:

**Comment by norihiro-w** [comment]
yes sorry I should have written that at the beginning. this PR is fix up of #1548.

**Pull request merged**
