### PR TITLE
Use <cmath> constants of sqrt(2) and 1/sqrt(2) for the Kelvin vector related computation 

### PR DESCRIPTION
**Pull request by wenqing**
As titled.

### CODE REVIEW

**Comment by endJunction** [comment]
What is the performance benefit?

**Comment by endJunction** [comment]
And the boost library already contains all of this constants and many more, is very well maintained and tested. Why?

**Comment by endJunction** [comment]
Can you show the machine dependent difference, please, which is resolved by adding name aliases?

**Comment by wenqing** [comment]
> What is the performance benefit?

At least, not compute sqrt(2).

**Comment by wenqing** [comment]
> And the boost library already contains all of this constants and many more, is very well maintained and tested. Why?

It uses boost constants but with name alias. If std have constants, we just change that that name aliases. Anyway, the name alias file, MathConstant.h, can be dropped, and this PR is only for using boost::root_two.

**Comment by wenqing** [comment]
> Can you show the machine dependent difference, please, which is resolved by adding name aliases?

See my reply above.

**Comment by TomFischer** [comment]
> > What is the performance benefit?
> 
> At least, not compute sqrt(2).

Is this constant expression really evaluated at run time?

**Comment by wenqing** [comment]
> > > What is the performance benefit?
> > 
> > 
> > At least, not compute sqrt(2).
> 
> Is this constant expression really evaluated at run time?

I am not sure that different compilers, or different compilers on difference OSs give the same sqrt(2).I 

I will change this PR for use <cmath> constant of  M_SQRT2.

**Pull request closed without merging**
