### PR TITLE
[Cmake] Make git secondary working directory work

### PR DESCRIPTION
**Pull request by chleh**
Starting from git 2.5 one can create secondary working directories using `git worktree add ...`.
This PR extends our CMake configuration s.t. it works on secondary working directories.

### CODE REVIEW

**Comment by TomFischer** [comment]
What is a secondary working directory and how is it used?

**Comment by chleh** [comment]
Sorry, gave the wrong command above.
A secondary working directory allows to check out two different branches to two different directories. Those two worktrees will then operate on the same repository.

See also: https://git-scm.com/docs/git-worktree

I thought this feature might be useful to have in OGS6 development.

**Comment by TomFischer** [comment]
Thank you for the explanation.

**Comment by wenqing** [comment]
:+1:

**Pull request merged**
