### PR TITLE
[NL] Remove unused time discretization schemes.

### PR DESCRIPTION
**Pull request by endJunction**
This are all but backward Euler.

 - All processes using a Newton scheme are discretized
for the backward Euler scheme only. They are not usable
with other time discretizations.
 - Greatly simplifies code maintenance in this part.

1. [x] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
2. [x] Tests covering your feature were **removed**?
3. [x] Any new feature or behavior change documentation was removed?

### CODE REVIEW

**Comment by endJunction** [comment]
I'd like to hear your opinions on the Crank-Nicolson scheme. It is only used in H2-pp quasinewton tests. To keep approximately same error with the Backward Euler method the runtime doubles.

**Comment by wenqing** [comment]
It can be removed. For large time step size or large spatial dicretization size, the scheme has less advantages over the the backward Euler scheme.

**Comment by endJunction** [comment]
Someone with good knowledge of the changed tests, please have a detailed look on the new results.

**Comment by endJunction** [comment]
Any comments?

**Comment by endJunction** [comment]
@nagelt ?

**Comment by endJunction** [comment]
OK, there is not much interest in this things, it seems. Merging tonight, unless there are more comments.

**Comment by nagelt** [comment]
> Looks fine.
> @nagelt Do we need to consider dynamic deformation in future?

Not in any of the currently upcoming projects (unfortunately). But I do hope that we'll include this eventually once we get a suitable project. Then, afaik, we have several options regarding the chosen time integration scheme.

**Comment by wenqing** [comment]
@endJunction  The associated parameter documentations were forgotten to remove.
https://doxygen.opengeosys.org/project_file_doc_qa.html

**Comment by endJunction** [comment]
Thanks. Will fix in the #2925 together with the large tests tolerances.

**Pull request merged**
