### PR TITLE
Explicit instantiation of GroundwateFlowProcess<GlobalSetup>.

### PR DESCRIPTION
**Pull request by endJunction**
This decouples the ogs.cpp compilation unit from the GroundwaterFlowProcess.

@chleh Is this compatible with your implementation of the TES process?

### CODE REVIEW

**Comment by chleh** [comment]
As far as I understand, this PR effects that not all processes will be recompiled each time only a single process is changed.
In my implementation I have "deactivated" some template parameters, especially for shape matrices. Thus, my code will not be compiled once for every possible shape matrix type.

**Comment by chleh** [comment]
:+1:

**Comment by bilke** [comment]
:+1:

**Comment by endJunction** [comment]
Jenkins, test this please!

**Comment by endJunction** [comment]
OK, Jenkins is reporting green again.

**Comment by chleh** [comment]
:+1:

**Pull request merged**
