### PR TITLE
Warnigs cleanup

### PR DESCRIPTION
**Pull request by endJunction**
See commit messages.
For the removed calls I assumed there are no side-effects.

### CODE REVIEW

**Comment by endJunction** [comment]
OK, the tests are passing now.

**Comment by TomFischer** [comment]
:+1:

**Comment by endJunction** [comment]
@bilke could you have a look into vtkvisPiplineView change please?

**Comment by TomFischer** [comment]
The vtkvisPiplineView change is okay. I had the same change in my PR #1019 .

**Pull request merged**
