### PR TITLE
[DataExplorer] Write gmsh geo format using fixed mesh density.

### PR DESCRIPTION
**Pull request by TomFischer**

### CODE REVIEW

**Comment by TomFischer** [comment]
@rinkk Please could you check if this is the expected output?

**Comment by waltherm** [comment]
Building does not finish for the MAC setup; @bilke can you have a look?

**Comment by endJunction** [comment]
@waltherm The particular test fails on that particular mac machine. Wenqing is looking into the details.
Can be merged, when desired behaviour is confirmed. Though a test case would be good addition.

**Comment by waltherm** [comment]
I cannot run the DataExplorer:
`./DataExplorer: error while loading shared libraries: libOGSFileConverterLib.so: cannot open shared object file: No such file or directory
`

**Comment by TomFischer** [comment]
@waltherm I rebased just now onto the actual master where the problem:
```./DataExplorer: error while loading shared libraries: libOGSFileConverterLib.so: cannot open shared object file: No such file or directory```
should be fixed.  When jenkins has finished the new build its ready for the test.

**Comment by waltherm** [comment]
I cannot write a gmsh (.geo) file. Enclosed is the log. And a test file (.shp).

[log.txt](https://github.com/ufz/ogs/files/2940847/log.txt)
[merged_simplify_reprojected_study_area.tar.gz](https://github.com/ufz/ogs/files/2940850/merged_simplify_reprojected_study_area.tar.gz)

**Comment by TomFischer** [comment]
From the log I cannot see what is wrong. What steps did you do?

**Comment by waltherm** [comment]
Strange... today it worked. At least saving the file. But I still have all the additional points saved in the .geo (gmsh) file. (File -> Save as -> .geo).

**Comment by TomFischer** [comment]
Did you use the DataExplorer build in this pull request?

**Comment by waltherm** [comment]
Sorry, @TomFischer, I really thought to have used this version last week. I tried again and it works: no extra points when importing a shp and exporting this as a gmsh file. Thanks!

:+1:

**Pull request merged**
