### PR TITLE
Take prj file and create links to Doxygen docu

### PR DESCRIPTION
**Pull request by chleh**
The main part is the script `scripts/doc/linked-xml-file.py`. The rest is Doxygen docu fixes, and documentation script improvements.

The result of the script looks as follows:
docu

The blue tags are links to the respecitive documentation pages. The red text marks tags whose documentation pages could not be found by the script.

This PR is meant to provide a more intuitive entry point to the project file documentation.

### CODE REVIEW

**Comment by chleh** [comment]
Just added a part to the QA page that shows which parameters are not ctested.

**Comment by endJunction** [comment]
The results look good!
I'm not sure how to review this, by commits or in single chunk. Maybe an overview of all the scripts and stuff would help.
Needs discussion.

**Comment by chleh** [comment]
I'm going to squash some the commits. Afterwards commit-wise review. I can add some general comments to the changed scripts.

**Comment by chleh** [comment]
Please review commit-wise.
Every script now has a short note about what it does. For the interplay of scripts see `generate-project-file-doc-qa.sh`.

**Comment by TomFischer** [comment]
I tried it out and it looks useful. :fast_forward:

**Comment by endJunction** [comment]
:fast_forward:

**Pull request merged**
