### PR TITLE
[Jenkins] Always archive build artifacts

### PR DESCRIPTION
**Pull request by bilke**
This enables downloading of binaries on each Pull Request.

As requested by @norihiro-w.

### CODE REVIEW

**Comment by bilke** [comment]
It fails to update the GitHub commit status, I do not know why.. Everything else is fine.

**Comment by norihiro-w** [comment]
because of this?
```
10:44:51 [mac] Archiving artifacts
10:44:51 [mac] ERROR: No artifacts found that match the file pattern "build/*.tar.gz,build/*.dmg". Configuration error?
10:44:52 [mac] ERROR: ‘build/*.tar.gz’ doesn’t match anything: ‘build’ exists but not ‘build/*.tar.gz’
```

**Comment by bilke** [comment]
I [fixed](https://gitlab.opengeosys.org/bilke/jenkins-library/commit/4083e821a56076152bded0ce237b303148fb4841) the Mac archiving error but still it fails on updating the GitHub commit status.

**Comment by endJunction** [comment]
Looks fine to me. When it is to you :fast_forward:

**Comment by bilke** [comment]
Everything is fine now.

https://gitlab.opengeosys.org/bilke/jenkins-library/commit/d0b7fd022f32e7b9f7e3f6def9bdc46e70daa196

**Comment by norihiro-w** [comment]
great! thank you

**Pull request merged**
