### PR TITLE
Move Gmsh to FileIO

### PR DESCRIPTION
**Pull request by TomFischer**
Reunite Gmsh interface implementations in the subfolder Applications/FileIO/Gmsh/.

### CODE REVIEW

**Comment by TomFischer** [comment]
The "Jenkis: OGS-6/Win-PRs" failed with: 
> ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@240bbc7[name=visserv3]

I guess this has nothing to do with the changes in the PR.

**Comment by rinkk** [comment]
:+1:

**Comment by norihiro-w** [comment]
:+1:

**Comment by TomFischer** [comment]
Rebased to fixed merge conflicts.

**Pull request merged**
