### PR TITLE
[PL] Resolve circular dep. HTBHE<->BC.

### LINKED ISSUE #2327: some circular dependency found
By chance, I found some circular dependency in the codes (see example below). Is there a plan to solve them at some time? or keep them as they are?  
- ProcessLib <--> MaterialLib (e.g. PorousMedium/Permeability)
- HeatTransportBHE  <--> ProcessLib (BoundaryCondition)

### PR DESCRIPTION
**Pull request by endJunction**
Passing the bhe type to the BCs is not necessary, just a callback.

Closes #2327

### CODE REVIEW

**Comment by norihiro-w** [comment]
To me, the fix is solving only technical dependency issue. Logical dependency still exists. Is it so difficult to move the HTBHE-specific bc code into HTBHE process module?

**Comment by endJunction** [comment]
@bilke Could you have a look, please, on the jenkins build; there are warnings, which I thought are excluded from the parsing: https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-2429/3/gcc4-gui/new/

**Comment by bilke** [comment]
@endJunction Same on [master](https://jenkins.opengeosys.org/job/ufz/job/ogs/job/master/962/gcc4-gui/new/). Yesterday I updated the warnigs parser plugin which has [some changes in the gcc parser](https://github.com/jenkinsci/analysis-model/commit/fcc6067b2c69f279afb1296218a7ccecf32f37b2), maybe its a bug in the parser.

**Comment by bilke** [comment]
@endJunction I created a bug report: 
https://issues.jenkins-ci.org/browse/JENKINS-56612

**Comment by bilke** [comment]
@endJunction Here is the fix (not live yet):

https://github.com/jenkinsci/analysis-model/commit/44e3b6db7f576bd4cf100d39f0e1bfece56799d0

**Comment by norihiro-w** [comment]
@endJunction Many thanks for the changes!

**Pull request merged**
