### PR TITLE
Cleanup GEOTYPE

### PR DESCRIPTION
**Pull request by chleh**
Removed the currently unused enum entries VOLUME and GEODOMAIN, and additionally INVALID

This fixes the bug described in #1111. (namely this change: https://github.com/ufz/ogs/compare/master...chleh:cleanup-geotype?expand=1#diff-7e6eac2bfd65d7d0c47ec78c1657e7c2L559)

### CODE REVIEW

**Comment by endJunction** [comment]
:fast_forward:

**Comment by endJunction** [comment]
BTW, @rinkk, could you have a look please if this works with the DE?

**Comment by rinkk** [comment]
Yes, but it'll have to wait until after we're back. Sorry.

**Comment by TomFischer** [comment]
Compilation of DataExplorer works. All ctest passed.

**Comment by TomFischer** [comment]
Looks good. :+1:

**Comment by chleh** [comment]
Shall I wait with the merge until someone (e.g. @rinkk) has done a real test of the DE?
Because that:
> Compilation of DataExplorer works. All ctest passed.

is also checked by Jenkins, right?

**Comment by TomFischer** [comment]
I am unsure what is meant by *real* test of DE?

**Comment by rinkk** [comment]
Everything seems to work fine. :+1:

**Pull request merged**
