### PR TITLE
Updated vtkdiff

### PR DESCRIPTION
**Pull request by chleh**
* File IO errors detected earlier
* Some more information printed
* Rel/abs tol fixed.

### CODE REVIEW

**Comment by endJunction** [comment]
:fast_forward: after the ctests are passing.

**Comment by chleh** [comment]
Tests pass as far as I can see.

**Comment by TomFischer** [comment]
Why do you need to make the relative tolerance weaker than before?

**Comment by chleh** [comment]
Because before vtkdiff did not use the RELTOL value but the ABSTOL value for relative tolerances. Cf. ufz/vtkdiff@38e1bce37466d3ab39b7e58d63e184a9693980c5

**Comment by TomFischer** [comment]
Thanks for clarification. :+1:

**Pull request merged**
