### PR TITLE
[CL] Bugfix dropped_item_ids

### PR DESCRIPTION
**Pull request by joboog**
Fixes as data I/O phreeqc-ogs

### CODE REVIEW

**Comment by renchao-lu** [comment]
Good catch. Thanks. @joboog

**Comment by endJunction** [comment]
A test would be great, because later someone could change the code and reintroduce the same bug.
If an existing test can be modified, that would be sufficient.

**Comment by renchao-lu** [comment]
I will modify the existing KineticReactant Benchmark to add two more kinetic reactants, as I need to reuse the test.dat file Vanessa and you created instead of the revised_llnl.dat file anyway. @joboog

**Comment by renchao-lu** [comment]
Done! 
1) Compressed the original thermodynamic database 
2) Modified the KineticReactant Benchmark for testing
Please cherry-pick the latest commit from my branch `feat_bugfix_CL` (https://github.com/renchao-lu/ogs6/tree/feat_bugfix_CL). @joboog

**Comment by montoyav** [comment]
I have had a fast look, and I see that all the products are considered as "PHASES" which means immobile mass. Probably, this was the intention (and numerically is correct), but I think this is not clear from the benchmark description.

**Comment by joboog** [comment]
@montoyav : there is no description for the test KineticReactant. Do not mix up with the test `KineticReactant_AllAsComponents` that is described on the webpage.

**Comment by montoyav** [comment]
OK, I see. My mistake.

**Comment by endJunction** [comment]
@renchao-lu When OK from your side, please rebase and merge.

**Pull request merged**
