### PR TITLE
Container with Python enabled

### LINKED ISSUE #2759: Include python-bindings in ogs module on eve cluster?
It would be nice if the ogs module on the eve cluster is able to use python boundary conditions and source terms.
Hence, I would highly approve, if the module loaded with

`module load ogs`

would support python bc and source terms.
@bilke

### PR DESCRIPTION
**Pull request by bilke**
Builds Singularity serial image with Python enabled and utils.

Closes #2759, #2761.

1. [x] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
3. [x] Any new feature or behavior change was documented?

### CODE REVIEW

**Comment by bilke** [comment]
@jbathmann You can test this right now:

- Download the container to eve: https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-2765/3/artifact/_out/images/ogs-c8f2efdc-serial-system-cmake-2593a41c-18560cbfc781.sif
- Run your OGS-Python benchmark with the container, [see docs](https://www.opengeosys.org/docs/userguide/basics/container/#run-ogs-inside-a-container-called-from-outside)

**Comment by jbathmann** [comment]
@bilke Thanks for this solution.

While testing, the following issue arose: If I start ogs from the container, my python environment is not activated within the container.
Using the container's shell, I can activate the environment manually, but only if I execute the "singularity shell"-command from a parent directory of the python environment.
However, the environment is not mounted automatically, if I run "singularity exec ..." resulting in missing python packages when ogs accesses the script for source terms and boundary conditions.

My script should be working, if the environment has access to the packages "vtk", "os" and "numpy". Is it possible to include this packages directly to the environment as a first workaround?

**Comment by bilke** [comment]
@jbathmann Thanks for testing!

**One thing to keep in mind:** mixing the Python environment (the virtualenv) from the host with the Python installation in the container I guess only works when both Python versions match...

I added the `--pip`-option to the [ogs-container-maker](https://www.opengeosys.org/docs/userguide/basics/container/#option-create-custom-image-with-ogs-container-maker) so that you can easily create a container with some pre-installed Python packages, e.g.:

Screenshot_2020-01-20_E2uaax

You can download the resulting image [here](https://jenkins.opengeosys.org/job/ufz/job/ogs-container-maker/job/master/223/artifact/_out/images/ogs-d43fd16b-serial-system-cmake-2593a41c-1cd0050cd9e0.sif). Please test it and let me know if it works for you.

**Comment by bilke** [comment]
@jbathmann [Update image](https://jenkins.opengeosys.org/job/ufz/job/ogs-container-maker/job/master/224/artifact/_out/images/ogs-d43fd16b-serial-system-cmake-2593a41c-499caed9e291.sif)

**Comment by jbathmann** [comment]
@bilke As discussed a testcase, which I am not able to run on frontend although it is working on my machine.
[Testcase](https://github.com/ufz/ogs/files/4086548/testcase.zip)

**Comment by jbathmann** [comment]
Before we forget, what is going on here and maybe to include @endJunction and @waltherm to the discussion:

OGS crashes (Segmentation fault) on eve, if a a python boundary condition imports vtk as in the following example:
https://github.com/ufz/ogs/files/4086548/testcase.zip

In this example, the use of python's vtk-package is necessary to determine in which cell (element) of the source mesh an integration point is located. I think such functionalities would be very useful for other end-users as well.

**Comment by endJunction** [comment]
So, with some tweaks it now, finally, crashes.
1. On current Archlinux I had replace the logog with spdlog (to avoid problem as described in #2861, see corresponding branch in my repo).
2. Then `nc_get_vara_schar` is not found:
```
[2020-03-17 20:42:40.888] [ogs] [info] This is OpenGeoSys-6 version 6.3.0-64-g5dc5476a3.dirty.20200317170730.
[2020-03-17 20:42:40.900] [ogs] [info] OGS started on 2020-03-17 20:42:40+0100.
[2020-03-17 20:42:40.901] [ogs] [debug] Project configuration from file '0_0_testmodel.prj' read.
[2020-03-17 20:42:40.901] [ogs] [debug] Reading multiple meshes.
[2020-03-17 20:42:40.901] [ogs] [debug] Reading mesh file 'testbulk.vtu'.
^[[A[2020-03-17 20:42:42.231] [ogs] [debug] Reading mesh file 'left_boundary.vtu'.
[2020-03-17 20:42:42.233] [ogs] [debug] Reading mesh file 'right_boundary.vtu'.
[2020-03-17 20:42:42.235] [ogs] [debug] Reading mesh file 'top_boundary.vtu'.
[2020-03-17 20:42:42.254] [ogs] [debug] Reading mesh file 'source_domain.vtu'.
[2020-03-17 20:42:42.423] [ogs] [warning] Array 'vtkGhostType' in VTU file uses unsupported data type 'unsigned char'. The data array will not be available.
[2020-03-17 20:42:42.423] [ogs] [warning] Array 'vtkGhostType' in VTU file uses unsupported data type 'unsigned char'. The data array will not be available.
[2020-03-17 20:42:42.424] [ogs] [debug] Binding Python module OpenGeoSys.
[2020-03-17 20:42:42.494] [ogs] [error] ImportError: /usr/lib/python3.8/site-packages/vtkmodules/../../../libvtkIONetCDF-pv5.8.so.1: undefined symbol: nc_get_vara_schar
```
The symbol is available in the /usr/lib/libnetcdf.so library which must be preloaded. Didn't look for reasons here.
3. Finally it crashes:
```sh
LD_PRELOAD=/usr/lib/libnetcdf.so.15 ~/w/ogs/xx/bin/ogs 0_0_testmodel.prj          
```
```
[2020-03-17 20:44:09.567] [ogs] [info] This is OpenGeoSys-6 version 6.3.0-64-g5dc5476a3.dirty.20200317170730.
[2020-03-17 20:44:09.589] [ogs] [info] OGS started on 2020-03-17 20:44:09+0100.
[2020-03-17 20:44:09.591] [ogs] [debug] Project configuration from file '0_0_testmodel.prj' read.
[2020-03-17 20:44:09.592] [ogs] [debug] Reading multiple meshes.
[2020-03-17 20:44:09.592] [ogs] [debug] Reading mesh file 'testbulk.vtu'.
[2020-03-17 20:44:10.981] [ogs] [debug] Reading mesh file 'left_boundary.vtu'.
[2020-03-17 20:44:10.983] [ogs] [debug] Reading mesh file 'right_boundary.vtu'.
[2020-03-17 20:44:10.985] [ogs] [debug] Reading mesh file 'top_boundary.vtu'.
[2020-03-17 20:44:11.005] [ogs] [debug] Reading mesh file 'source_domain.vtu'.
[2020-03-17 20:44:11.180] [ogs] [warning] Array 'vtkGhostType' in VTU file uses unsupported data type 'unsigned char'. The data array will not be available.
[2020-03-17 20:44:11.180] [ogs] [warning] Array 'vtkGhostType' in VTU file uses unsupported data type 'unsigned char'. The data array will not be available.
[2020-03-17 20:44:11.181] [ogs] [debug] Binding Python module OpenGeoSys.
ERROR: In /build/vtk/src/VTK-8.2.0/Common/ExecutionModel/vtkExecutive.cxx, line 372
vtkCompositeDataPipeline (0x55d6125ca570): Attempt to get input information vector from input port index -1052917024 for algorithm vtkXMLUnstructuredGridReader(0x55d6127bc360), which has 0 input ports.

[1]    106228 segmentation fault (core dumped)  LD_PRELOAD=/usr/lib/libnetcdf.so.15 ~/w/ogs/xx/bin/ogs 0_0_testmodel.prj
```

@jbathmann Is this the same output you get?

**Comment by endJunction** [comment]
With debug version of vtk I don't get any new information. The `vtkXMLUnstructuredGridReader` object exists, but is not initialized (all of the members are null).
I don't know for the moment how to proceed.

Callstack:
```
0x00007ffff72cc238 in vtkInformationVector::GetNumberOfInformationObjects (this=0x0) at /data/vtk/src/VTK-8.2.0/Common/Core/vtkInformationVector.h:49
49        int GetNumberOfInformationObjects() { return this->NumberOfInformationObjects; };
(gdb) bt
#0  0x00007ffff72cc238 in vtkInformationVector::GetNumberOfInformationObjects (this=0x0) at /data/vtk/src/VTK-8.2.0/Common/Core/vtkInformationVector.h:49
#1  0x00007ffff72c8aef in vtkAlgorithm::SetNumberOfInputConnections (this=0x555557cfe020, port=-200236160, n=-278781344) at /data/vtk/src/VTK-8.2.0/Common/ExecutionModel/vtkAlgorithm.cxx:1281
#2  0x00007fffef621e28 in ?? () from /usr/lib/python3.8/site-packages/vtkmodules/vtkIOXML.so
#3  0x00007ffff5decb6f in PyCFunction_Call () from /usr/lib/libpython3.8.so.1.0
#4  0x00007ffff5ddff42 in _PyObject_MakeTpCall () from /usr/lib/libpython3.8.so.1.0
#5  0x00007ffff5db6867 in ?? () from /usr/lib/libpython3.8.so.1.0
#6  0x00007ffff5e8a0dd in _PyFunction_Vectorcall () from /usr/lib/libpython3.8.so.1.0
#7  0x00007ffff5de5f2d in PyObject_Call () from /usr/lib/libpython3.8.so.1.0
#8  0x00007ffff5e9ade7 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.8.so.1.0
#9  0x00007ffff5e88f34 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.8.so.1.0
#10 0x00007ffff5e8a2bb in _PyFunction_Vectorcall () from /usr/lib/libpython3.8.so.1.0
#11 0x00007ffff5e992ae in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.8.so.1.0
#12 0x00007ffff5e8b840 in ?? () from /usr/lib/libpython3.8.so.1.0
#13 0x00007ffff5ddfd1a in _PyObject_MakeTpCall () from /usr/lib/libpython3.8.so.1.0
#14 0x00007ffff5e9d4d4 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.8.so.1.0
#15 0x00007ffff5e88f34 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.8.so.1.0
#16 0x00007ffff5f10873 in PyEval_EvalCode () from /usr/lib/libpython3.8.so.1.0
#17 0x00007ffff5f108c8 in ?? () from /usr/lib/libpython3.8.so.1.0
#18 0x00007ffff5f14ba3 in ?? () from /usr/lib/libpython3.8.so.1.0
#19 0x00007ffff5dafa1f in PyRun_FileExFlags () from /usr/lib/libpython3.8.so.1.0
#20 0x0000555555770f36 in pybind11::eval_file<(pybind11::eval_mode)2> (fname=..., global=..., local=...) at /home/naumov/w/ogs/s/ThirdParty/pybind11/include/pybind11/eval.h:108
#21 0x0000555555765930 in ProjectData::ProjectData (this=0x7fffffffd880, project_config=..., project_directory="", output_directory="") at /home/naumov/w/ogs/s/Applications/ApplicationsLib/ProjectData.cpp:291
#22 0x00005555556b0c36 in main (argc=2, argv=0x7fffffffdbd8) at /home/naumov/w/ogs/s/Applications/CLI/ogs.cpp:190
```
In frame 1 the `this` object exists, but everything there is 0, as also seen on the `this` value in frame 0.

**Comment by jbathmann** [comment]
@endJunction I get a similar output from ogs in debug mode.

`info: This is OpenGeoSys-6 version 6.2.2-327-gc6b4926ce.`
`info: OGS started on 2020-03-18 11:38:12+0100.`
`debug: Project configuration from file '0_0_testmodel.prj' read.`
`debug: Reading multiple meshes.`
`debug: Reading mesh file 'testbulk.vtu'.`
`debug: Reading mesh file 'left_boundary.vtu'.`
`debug: Reading mesh file 'right_boundary.vtu'.`
`debug: Reading mesh file 'top_boundary.vtu'.`
`debug: Reading mesh file 'source_domain.vtu'.`
`warning: Array 'vtkGhostType' in VTU file uses unsupported data type 'unsigned char'. The data array will not be available.`
`warning: Array 'vtkGhostType' in VTU file uses unsupported data type 'unsigned char'. The data array will not be available.`
`debug: Binding Python module OpenGeoSys.`
`Speicherzugriffsfehler`

**Comment by endJunction** [comment]
I'd say, if other python tests do run, then this PR can proceed. The project from the last testcase.zip is not running on the environments too.

And I'm also out of ideas on how to get that testcase running, for now.

**Comment by bilke** [comment]
@endJunction 

- Which vtk do you use? Looks like it is from ParaView (`libvtkIONetCDF-pv5.8.so.1`)
- If vtk was properly built, the symbol `nc_get_vara_schar` should be there, [defined here](https://gitlab.kitware.com/vtk/vtk/-/blob/v8.2.0/ThirdParty/netcdf/vtknetcdf/include/vtk_netcdf_mangle.h#L329)
- You should not **not** load / link another netcdf lib! VTK comes with its own and if you build VTK with its default settings it will also use its own netcdf lib

**Comment by endJunction** [comment]
Yes, there is a mismatch. On archlinux:
 - paraview is independent of vtk
 - vtk and paraview provide python bindings and there is a clash.
 - Both packages depend on netcdf.

Now I removed both and installed only vtk, and then it magically works out of the box.

Then Lars' suspicion about libraries mismatch on eve *etc.* is likely to be the cause of the problem.

**Comment by jbathmann** [comment]
Thanks to @endJunction and @bilke. 
Does this mean we could solve the issue by contacting the eve-cluster team?

**Comment by waltherm** [comment]
@jbathmann: I guess the best would be to place a ticket for the EVE team.

**Comment by bilke** [comment]
@endJunction From my side this can be merged, the generated container works and the issues discussed here are not specifically related to the container stuff.

**Pull request merged**
