### PR TITLE
SwmmInterface BugFix

### PR DESCRIPTION
**Pull request by rinkk**
fixed issue with non-unique points at beginning and end of polyline

### CODE REVIEW

**Comment by endJunction** [comment]
Please rebase to the 6.0.7 release tag before merging.

**Comment by endJunction** [comment]
A test would be desirable, otherwise this looks innocent.

**Comment by endJunction** [comment]
Also please wait until Jenkins finishes the builds....

**Comment by bilke** [comment]
At the time Karsten merged the Jenkins job did not show up because it has not been started. Therefore everything was green at that moment.

**Comment by endJunction** [comment]
Hmm, ;) we were talking about exactly that build 1465, there was gcc not yet finished...

**Comment by bilke** [comment]
Or it was started but this PR web page was not updated on Karstens side..

**Pull request merged**
