### PR TITLE
[PL] shape matrices created in separate function

### PR DESCRIPTION
**Pull request by chleh**
As titled. Nothing fancy.

### CODE REVIEW

**Comment by endJunction** [comment]
Could you please describe why we need the changes?

**Comment by chleh** [comment]
Because those lines will be needed in every single local assembler that will be written. There are no changes, only a move of code.

**Comment by wenqing** [comment]
I see.

**Comment by chleh** [comment]
Do you have any further comments? This is a really small PR, so I hope, it can be merged fast.

**Comment by TomFischer** [comment]
:fast_forward:

**Pull request merged**
