### PR TITLE
correction of density calculation in thermo-mechanics

### PR DESCRIPTION
**Pull request by xingyuanmiao**
As titled. This correction has been done in thermo-mechanical phase-field process.

### CODE REVIEW

**Comment by wenqing** [comment]
The corresponding benchmark failed.

**Comment by wenqing** [comment]
@xingyuanmiao 
I just requested a change. Please don't make change before @endJunction  and @nagelt review it.

**Comment by endJunction** [comment]
Setting WIP until the requested documentation is provided.

**Comment by xingyuanmiao** [comment]
which kind of documentation should be provided?

**Comment by xingyuanmiao** [comment]
The derivation of the calculation of real density is added in the code and documentation.

**Comment by endJunction** [comment]
As mentioned before, please add the incompressibility assumption to the formulae. There must be some text describing the formulae...

> The computation of solid's density is correct under the assumption of incompressible solid grains. This **must** be mentioned in the code and documentation of the `rho_sr` parameter. Also the derivation of this formula is to be included.

**Comment by xingyuanmiao** [comment]
provided a reference to explain the formula.

**Comment by endJunction** [comment]
I, unfortunately, don't see how the formula is explained in the referenced paper, there is even no discussion on density computation. Furthermore, the paper shows that the assumption of solid's "incompressibility implies thermal inexpansibility" (see eq. 4 there). The latter is not the point of TM implementation.

The explanation of the solid's density computation is still to be explained.

For the references, please use `\cite` and proper bibtex entries.

**Comment by nagelt** [comment]
The original Ansatz made is \rho_{SR} = \rho_{SR0} exp (- 3 \alpha_T \Delta T) for large thermal strains. Once we linearize around \Delta T = 0 and truncate the Taylor series after the first member, the end result is \rho_{SR} = \rho_{SR0} / ( 1 + 3 \alpha_T \Delta T). You can also arrive at the result by assuming a linear volume strain from the start: e = 3 \alpha_T \Delta T. The key assumption is that the solid density is independent of pressure, i.e. \rho_{SR} = \rho_{SR}(T).

**Pull request merged**
