### PR TITLE
[Jenkins] clang-tidy checks

### PR DESCRIPTION
**Pull request by bilke**
Introduces new sub-job `Clang-Analyzer`. Set unstable threshold to current number of clang-tidy issues (58).

@endJunction Had to update clang to version 7 (and the base image of the Docker container to Ubuntu 18.04) to fix linker errors.

### CODE REVIEW

**Comment by endJunction** [comment]
@bilke I extracted the two commits for clang-tidy and clang-format configs; now in master.

**Comment by endJunction** [comment]
Tried with clang-tidy on my machine---it works too...

**Comment by endJunction** [comment]
Just an idea: The `-fPIC` mismatch error could be related to precompiled headers...

**Comment by bilke** [comment]
@endJunction No, I had to add `-fpic` to shapelib and cvode Conan packages.

Ready for review (everything is green except one failing unit test which sometimes fails).

**Comment by endJunction** [comment]
@ufz/members 

I've added "few" of generic changes to the PR handling the clang-tidy checks regarding the
 - namespace comments
 - braces around if/else/for etc. blocks
 - and some of the else after return cases.

There will be conflicts with current PRs and other branches. If somebody has objections to the big changes, now is good time to talk about it.

**Comment by endJunction** [comment]
@bilke Sometimes on a mac the `2D_Adaptive_dt_ThermalConvection_constviscosityStaggeredScheme` ctest runs in just 62 seconds,
and sometimes times out after 900s. Some hidden work on a mac-slave?

[passes](https://jenkins.opengeosys.org/blue/organizations/jenkins/ufz%2Fogs/detail/PR-2377/24/pipeline/52/) in the last build, but [time out](https://jenkins.opengeosys.org/blue/organizations/jenkins/ufz%2Fogs/detail/PR-2377/23/pipeline/54) in previous build.

**Comment by bilke** [comment]
@endJunction The passed build ran on vismac05 which is a current Mac model whereas the timed out benchmark ran on vismac02 which is from 2012 or so... No hidden work on the slaves.

**Pull request merged**
