### PR TITLE
Eigen assertions enabled by default

### PR DESCRIPTION
**Pull request by chleh**
See issue #881.
I think setting Eigen assertions to "ON" by default is a better choice than disabling them.

### CODE REVIEW

**Comment by chleh** [comment]
Jenkins already found out about the sane new default :smile:

**Comment by chleh** [comment]
Sorry, I don't see the issue in the test immediately. Maybe someone of you sees easily why the test fails. Can you please help me fixing it?

**Comment by bilke** [comment]
There was an assertion triggered:

```
testrunner: /gpfs1/data/ogs/jenkins/workspace/OGS-6/Linux-PRs/build/External/eigen/src/Eigen/Eigen/src/Core/DenseCoeffsBase.h:337:
Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index, Eigen::DenseCoeffsBase<Derived, 1>::Index)
[with Derived = Eigen::Matrix<double, -1, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]:
Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
```

**Comment by chleh** [comment]
Thanks, but I also saw, that the assertion was triggered. Maybe, I should have said that.
I thought, maybe someone knows how to fix the constructor of `NumLibFemIsoTest` properly.
in particular: What to change s.t. the product `globalD = R^T D R` is meaningful AND the tests pass?

**Comment by chleh** [comment]
The last commit fixes an assertion violation with Neumann BCs. I think there is a problem with the constructors and `resize()` methods of the shape matrices: They both come in versions with and without a `global_dim` parameter. This difference can be easy overlooked. So I suggest to drop the methods without `global_dim` parameter. Though this must be done in a subsequent PR.

**Comment by endJunction** [comment]
Replaced by https://github.com/ufz/ogs/pull/904 without the GroundwaterFlow changes.

**Pull request closed without merging**
