### PR TITLE
Conan package manager

### PR DESCRIPTION
**Pull request by bilke**
Contains (optional) usage of the Conan package manager, see #1103 for details.

## Conclusions:

All required packages for CLI as well as the Data Explorer are available and in my opinion it works really nice. I have set up a [documentation on its usage](https://docs.opengeosys.org/docs/devguide/getting-started/conan-package-manager).

### Further changes:

- Travis jobs are now explicitly defined (under `matrix:`, `include:`)
- Added one Travis job to test Conan
- Removed bundled shapelib
- Added a git submodule for `vtkGUISupportQt` which removes the requirement that VTK has to built with Qt support enabled. A simple VTK build is enough as the Qt support is built by OGS.

### TODO (can be done later):

- [ ] Build GUITravis jobs cannot install shapelib, depends on travis-ci/apt-package-whitelist#2858, jobs are currently disabled and will be enabled later on

### CODE REVIEW

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by TomFischer** [comment]
Only to ensure that I understand it correctly: It will be possible to use the lib version from the operating system package management?

**Comment by bilke** [comment]
Yes, current lib searching behavior is not changed. You have to explicitly use the package manager (by running `conan install [path-to-source-folder]` in your build-folder).

**Comment by TomFischer** [comment]
Are there any open points or is the PR ready for merge?

**Comment by bilke** [comment]
It is ready to merge.

**Comment by TomFischer** [comment]
Although I do not understand the details: :fast_forward:

**Pull request merged**
