### PR TITLE
Added an optional input of reference temperature for LiquidFlow

### PR DESCRIPTION
**Pull request by wenqing**
This PR contains:
Fluid property: Changed the first letter of four file names to capital letter.
Liquid flow: Added an optional input of reference temperature for LiquidFlow.

### CODE REVIEW

**Comment by endJunction** [comment]
@bilke Could you have a look on the Jenkins' log messages; it seems to me that there is a mismatch between the lfs hash in the repo and an available on the server...

**Comment by wenqing** [comment]
@bilke What is this error message?
```
hudson.plugins.git.GitException: Could not checkout 7d394aa60e1ba9b102571c8e220a797ba111d857
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2063)
```
(see: https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-1730/4/console)

**Comment by bilke** [comment]
@wenqing There was `git-lfs` missing in one the build images. [I have added it](https://github.com/ufz/dockerfiles/commit/14f45afd2ca3a017b10b9a4522ddfcffc40eb2ac) and now everything is green.

**Comment by wenqing** [comment]
@bilke Thanks.

**Pull request merged**
