### PR TITLE
Extrapolator releases global vectors again

### LINKED ISSUE #1172: Matrices and vectors in use after end of tests.
Jenkins reports:
> There are still some matrices and vectors in use. This might be an indicator of a possible waste of memory.

### PR DESCRIPTION
**Pull request by chleh**
Fixes #1172.

### CODE REVIEW

**Comment by TomFischer** [comment]
:fast_forward:

**Comment by chleh** [comment]
Just gonna merge that tiny thing now.

**Comment by chleh** [comment]
Interesting: Github auto-closed the associated issue...

**Comment by endJunction** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/

**Pull request merged**
