### PR TITLE
Enable BUILD_SHARED_LIBS=ON on Windows

### PR DESCRIPTION
**Pull request by bilke**

### CODE REVIEW

**Comment by endJunction** [comment]
Microsoft has an interesting limit for linker:
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1189?view=vs-2017
> The limit of 65535 objects or members in a library has been exceeded.
> To fix this issue, split your library into two or more libraries with fewer objects or members.

**Comment by endJunction** [comment]
@bilke I've rebased the branch. Trying one more time to get all shared libraries on win, otherwise the last commit shall be dropped.

**Comment by bilke** [comment]
@endJunction I added one more fix for the ParameterLib and rebased too, still: `LNK1189: library limit of 65535 objects exceeded`

**Comment by endJunction** [comment]
=> static ProcessLib.

**Comment by bilke** [comment]
Same for `ComponentTransport.dll` ...

**Comment by bilke** [comment]
This feature is no priority at the moment.

**Pull request closed without merging**
