### PR TITLE
[web] Publications page

### PR DESCRIPTION
**Pull request by bilke**
- Added a publications page to the web site, [see preview](https://deploy-preview-2981--ogs.netlify.app/publications/)
- Added citation info to the docs overview page, [see preview](https://deploy-preview-2981--ogs.netlify.app/docs/)
- Publication data is generated with [pybtex-convert](https://docs.pybtex.org/cmdline.html) from Bibtex to yaml to feed the web site generator (needs to be re-run when the bib-files are changed)
- Migrated web site icons to local copy instead of CDN, minimized size

1. [ ] Feature description was added to the [changelog](https://github.com/ufz/ogs/wiki/Release-notes-6.3.1)
3. [x] Any new feature or behavior change was documented?

### CODE REVIEW

**Comment by endJunction** [comment]
Doxygen needs an update because of the changed .bib file.
https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-2981/5/doxygen/

**Comment by montoyav** [comment]
I also like it! I think this gives more visibility.
I have had a look the preview and I see that now we have duplicates. In "books folder" it appears books and tutorials and in publications also appears the books and tutorials included in the other folder. Will the sections books be deleted?
In addition there are some references that are not related to the implementation of OGS ;-) so references should be checked. I miss in publications a subfolder on "benchmarks" 

In addition and maybe this is out of this discussion. In any moment we should speak how we include the third party chemical thermodynamic databases we are using in reactive transport in the webpage (as well for having visibility).

**Comment by bilke** [comment]
@endJunction Doxygen fixed.

@montoyav Thanks for your comments! I restructured a bit: https://deploy-preview-2981--ogs.netlify.app/publications/

There are now 3 clear sections (paper, books, tutorials). The paper also include a category. Feel free to clean up and add to the list (in `Documentation/bibliography/ogs.bib`) in a subsequent PR, this would be a good opportunity to contribute!

**Comment by endJunction** [comment]
If no further comments, can be merged tonight...

**Comment by montoyav** [comment]
OK, I will help to update the literature in a subsequent PR

**Pull request merged**
