### PR TITLE
Separate GroundwaterFlow process parser from its ctor.

### PR DESCRIPTION
**Pull request by endJunction**
Review commit-wise. There should be no behavioural changes.

~~@chleh Needs discussion on what is going into the base Process class...~~
Update: Extract common functions for
- [x] find variable
- [x] find parameter.

### CODE REVIEW

**Comment by bilke** [comment]
:+1:

**Comment by wenqing** [comment]
Looks better. :+1:

**Comment by chleh** [comment]
:+1: in general. Now GWFPcs is at its bare minimum.
The documentation of the `find...()` functions can be extended. However, for the time being this is not so important. Just add some TODO notes to the corresponding sections. I guess, in a few weeks we will have to do some documentation work anyway, and this point can be addressed then, too.

**Comment by endJunction** [comment]
Fixed doxygen docs...

**Comment by chleh** [comment]
:fast_forward:

**Pull request merged**
