### PR TITLE
[MeshLib] Add char and bool properties to VtkMeshConverter.

### PR DESCRIPTION
**Pull request by TomFischer**
This PR deals with the conversion of `vtkCharArray` and `vtkBitArray` to `PropertyVector`. These conversion is needed for a tool (PR in preparation).

### CODE REVIEW

**Comment by chleh** [comment]
:+1:
Looks reasonable for me.

**Comment by endJunction** [comment]
Jenkins, test this please!

**Comment by TomFischer** [comment]
Forgot at least one commit. Will reopen the PR later.

**Comment by TomFischer** [comment]
Added the commit for transmiting a char vector to InSituLib::VtkMappedMeshSource.

**Pull request merged**
