### PR TITLE
rename LocalToGlobalIndexMap::getNumXXX() to getNumberOfXXX()

### PR DESCRIPTION
**Pull request by norihiro-w**
follow up of #1243 which I forgot renaming

### CODE REVIEW

**Comment by endJunction** [comment]
:fast_forward:

**Comment by endJunction** [comment]
Extrapolation test failed...

**Comment by endJunction** [comment]
Jenkins, test this please!

**Comment by norihiro-w** [comment]
Jenkins test this please!

**Comment by norihiro-w** [comment]
@chleh A test of Extrapolation is failing. Do you have any idea what's going on? 

[ RUN      ] NumLib.Extrapolation
/home/jenkins/workspace/OGS-6/Docker/ufz/PR-1280/ogs/Tests/NumLib/TestExtrapolation.cpp:281: Failure
Expected: (tolerance_res) > (res_norm), actual: 8.88178e-16 vs 9.9483e-16
[  FAILED  ] NumLib.Extrapolation (1160 ms)

**Comment by chleh** [comment]
This is probably OK. The extrapolation test generates random data. Sometimes the computed errors are a bit higher, sometimes a bit lower. Unti now we raised the tolerance step-by-step, hoping that the test will fail in less often in the future. I think that's OK, because the tolerances are still pretty strict.

I raised the tolerance in master to

**Comment by chleh** [comment]
btw: :+1:

**Comment by norihiro-w** [comment]
i see. thanks

**Pull request merged**
