### PR TITLE
[CMake] Added option OGS_EIGEN_INITIALIZE_MATRICES_BY_NAN.

### PR DESCRIPTION
**Pull request by bilke**
Defaults to ON.

~~Set EIGEN_NO_AUTOMATIC_RESIZING macro as well.~~
See https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html.

Related to #1909.

### CODE REVIEW

**Comment by endJunction** [comment]
Perfect! It immediately catched a bug! :fireworks:
I'll provide a fix shortly.

**Comment by chleh** [comment]
:+1:

**Comment by bilke** [comment]
@endJunction I have added Eigen 3.3.4 as a Conan package: https://github.com/bilke/conan-eigen3/commit/6e8d4332fd88791c0fa33823fed04dd96e9b5317

**Comment by endJunction** [comment]
I've removed the EIGEN_NO_AUTOMATIC_RESIZING option for now, so the PR can be merged soon.
The automatic resizing option needs more work and I was not able to reproduce the behaviour seen on travis on my local machine.

**Comment by endJunction** [comment]
Needs one more review and can be merged if OK.

**Comment by endJunction** [comment]
OK. While nobody is listening, I'll merge it quietly ;)

**Pull request merged**
