### PR TITLE
Petsc/mpi tests.

### PR DESCRIPTION
**Pull request by endJunction**
Three commits unrelated to each other:
Adding one test. Change configuration of petsc/mpi tests.

### CODE REVIEW

**Comment by bilke** [comment]
:+1:

**Comment by bilke** [comment]
Will there be MPI tests in the future (via ctest)?

**Comment by wenqing** [comment]
@bilke MPI tests are still there but only for the code compiled with option ``USE_PETSC``.

**Comment by TomFischer** [comment]
Added test is not tested.

**Pull request merged**
