### PR TITLE
Corrected a documentation page reference

### PR DESCRIPTION
**Pull request by wenqing**
as titled.

### CODE REVIEW

**Comment by bilke** [comment]
This was fixed in dae430eea0.

**Comment by wenqing** [comment]
If no comment, it is going to be merged soon.

**Comment by endJunction** [comment]
@wenqing This isn't changing anything in the QA page. Please check the generated doxygen output before.

**Comment by wenqing** [comment]
@endJunction Ran make doc, the local Q&A page still links to the source of master.

**Comment by wenqing** [comment]
@chleh  It works. Thanks.

**Comment by wenqing** [comment]
After merging, Q&A page shows this correction a couple of minutes later.

**Pull request merged**
