### PR TITLE
CMake instructions for installing utilities

### PR DESCRIPTION
**Pull request by bilke**
Utilities will later on be available as binary downloads on ogs.org.

### CODE REVIEW

**Comment by endJunction** [comment]
Looks ok. How can we check/try this?
:fast_forward:

**Comment by TomFischer** [comment]
:+1:

**Comment by bilke** [comment]
If utils are build then `make install` installs the binaries into `${CMAKE_INSTALL_PREFIX}/bin`.

**Comment by bilke** [comment]
Utilities are now build in a separate Jenkins job (`OGS-6/*_Utils`) and binary downloads are available on http://docs.opengeosys.org/download under *Additional tools*.

**Comment by TomFischer** [comment]
Great work, so the user can download the tools now.

**Comment by norihiro-w** [comment]
:+1:

**Pull request merged**
