### PR TITLE
Allow C++17 language features.

### PR DESCRIPTION
**Pull request by endJunction**
The current minimum compilers must support it though.

### CODE REVIEW

**Comment by endJunction** [comment]
@bilke For the Eigen-3.2.10, I think a new branch in https://github.com/bilke/conan-eigen3/tree/release/3.2.9 is needed. Could you create one? I have no push permission there; Just two changes:
```diff
diff --git a/Jenkinsfile b/Jenkinsfile
index 9afb89d..4ec378a 100644
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -2,4 +2,4 @@
 
 // Implementation at:
 // https://github.com/ufz/jenkins-pipeline-library/blob/master/vars/conanBuild.groovy
-conanBuild("Eigen3/3.2.9")
+conanBuild("Eigen3/3.2.10")
diff --git a/conanfile.py b/conanfile.py
index 6151a0d..c7344f1 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -5,7 +5,7 @@ from conans.tools import download, unzip
 class Eigen3Conan(ConanFile):
     name = "Eigen3"
     description = "Eigen is a C++ template library for linear algebra"
-    version = "3.2.9"
+    version = "3.2.10"
     generators = "cmake"
     exports = ["FindEigen3.cmake"]
     url="http://github.com/bilke/conan-eigen3"
```

**Comment by bilke** [comment]
TODO self: Remove FindEigen3.cmake?

**Comment by endJunction** [comment]
@bilke maybe netlify also needs a --force for submodules?

**Comment by bilke** [comment]
@endJunction There is no way to configure git stuff.. I cleared the cache and rebuild, works.

**Comment by bilke** [comment]
@endJunction This is strange, on mac on running the tests `GeoLib.InsertTwoPointsInGrid` and `NumLibDistributionQuad.InterpolationSurface` (and maybe more) sometimes I get a segfault, and sometimes a malloc error:

```bash
Note: Google Test filter = GeoLib.InsertTwoPointsInGrid
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from GeoLib
[ RUN      ] GeoLib.InsertTwoPointsInGrid
testrunner(46498,0x10ca965c0) malloc: can't allocate region
*** mach_vm_map(size=2305825481739694080) failed (error code=3)
testrunner(46498,0x10ca965c0) malloc: *** set a breakpoint in malloc_error_break to debug
/Users/bilke/code/ogs6/ogs/Tests/GeoLib/TestGrid.cpp:42: Failure
Expected: GeoLib::Grid<GeoLib::Point> grid(pnts.begin(), pnts.end()) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] GeoLib.InsertTwoPointsInGrid (1 ms)
```
and
```bash
➜ bin/testrunner --gtest_filter=NumLibDistributionQuad.InterpolationSurface

Note: Google Test filter = NumLibDistributionQuad.InterpolationSurface
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from NumLibDistributionQuad
[ RUN      ] NumLibDistributionQuad.InterpolationSurface
testrunner(47852,0x10ece85c0) malloc: *** error for object 0x7000000000000000: pointer being freed was not allocated
testrunner(47852,0x10ece85c0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      bin/testrunner --gtest_filter=NumLibDistributionQuad.InterpolationSurface
```

Switching googletest from master to tag `1.8.1` did not help.

**Pull request merged**
