### PR TITLE
Use all available shape functions

### PR DESCRIPTION
**Pull request by endJunction**
This makes all currently implemented shape functions available for the local assemblers.

The mapping between mesh elements and the shape functions is one-to-one.
In general the higher-order shape functions can be instantiated on the lower-order mesh elements too. Those interested in this feel free to provide another template argument to the `LocalDataInitializer` for the order of shape functions and extend the builder map.

### CODE REVIEW

**Comment by norihiro-w** [comment]
:+1:

**Comment by endJunction** [comment]
Does anybody have an idea, why there are multiple definitions in the resulting object files?
When reverting the last commit, there are no compile errors.

**Comment by norihiro-w** [comment]
i have sent you a PR to fix the error.

**Comment by endJunction** [comment]
Just a rebase.

**Pull request merged**
