### PR TITLE
[FEFLOW] fix a bug that a property vector was not allocated before use

### LINKED ISSUE #1395: Data_explorer: FEFLOW IMPORT CRASHES
Version 6.0.2-406 works; was once the  commit 895b1124 (deleted?!)

Last version crashes  ae84365d

For input files pls contact me

### PR DESCRIPTION
**Pull request by norihiro-w**
follow up of #1400. fix #1395

### CODE REVIEW

**Comment by TomFischer** [comment]
Thanks for fixing the bug. Could you please provide a tiny example for our test suite?

:

**Comment by norihiro-w** [comment]
I added an example in https://github.com/ufz/ogs-data/pull/24, which is also used in the new test

**Comment by norihiro-w** [comment]
@fabienma can you please test this PR with your example?

**Comment by norihiro-w** [comment]
TODO: update the submodule Data

**Comment by fabienma** [comment]
file for test. Current version ogs-6.0.6-513-g51eaa5f- crashes when importing the FEM file
[feflw_import_test.zip](https://github.com/ufz/ogs/files/469646/feflw_import_test.zip)

**Comment by norihiro-w** [comment]
it works. The version you used is latest in master branch but is not including my modifications yet.
screen

**Comment by norihiro-w** [comment]
The Jenkins error on Mac is below and is not caused by this PR. maybe @bilke is changing something there

```
In file included from /Users/jenkins/workspace/OGS-6/Gui/Mac-PRs/ogs/Applications/DataExplorer/DataView/DirectConditionGenerator.cpp:22:
In file included from /Users/jenkins/workspace/OGS-6/Gui/Mac-PRs/ogs/Applications/FileIO/AsciiRasterInterface.h:20:
In file included from /usr/local/include/boost/optional.hpp:15:
In file included from /usr/local/include/boost/optional/optional.hpp:1035:
/usr/local/include/boost/optional/detail/optional_reference_spec.hpp:97:78: error: 'ptr_' is a private member of 'boost::optional<MeshLib::PropertyVector<int> &>'
        explicit optional(const optional<U&>& rhs) BOOST_NOEXCEPT : ptr_(rhs.ptr_) {}
                                                                             ^
/Users/jenkins/workspace/OGS-6/Gui/Mac-PRs/ogs/Applications/DataExplorer/DataView/DirectConditionGenerator.cpp:100:58: note: in instantiation of function template specialization 'boost::optional<const MeshLib::PropertyVector<int> &>::optional<MeshLib::PropertyVector<int> >' requested here
    boost::optional<MeshLib::PropertyVector<int> const&> opt_node_id_pv(
                                                         ^
/usr/local/include/boost/optional/detail/optional_reference_spec.hpp:83:8: note: implicitly declared private here
    T* ptr_;
       ^
1 error generated.
```

**Comment by endJunction** [comment]
@norihiro-w The last error look like those fixed in #1383 
The `optional<T const&>` is no longer valid. I changed it to `optional<T&> const`.

**Comment by bilke** [comment]
@norihiro-w See #1401.

**Comment by norihiro-w** [comment]
@bilke thanks

**Pull request merged**
