### PR TITLE
GML reader: Explicitly ignore polylines/surfaces without name

### PR DESCRIPTION
**Pull request by chleh**
This PR should fix the failing tests. It partially supersedes #1022.

### CODE REVIEW

**Comment by endJunction** [comment]
@chleh Now the behaviour btw. qt and boost xml is different. One could split the tests for qt from boost but then there is a chance that two compilations do read different things (depending on qt's presence).
Or update qt tests...

**Comment by endJunction** [comment]
To get the tests up and running fast I think it is best to add names to those polylines/surfaces for now. If there is a need to improve the tests regarding ignored polylines/surfaces (which is also affecting the qt parser), it should be done in different PR.

**Comment by chleh** [comment]
@TomFischer's fix rulez!

**Comment by endJunction** [comment]
@rinkk  Please have a look on this and merge, or mark for rebase&merge.

**Comment by rinkk** [comment]
i have no idea what happens here but it looks okay?

**Pull request merged**
