### PR TITLE
[BL] Quicksort: Fix miscalculated second limit.

### PR DESCRIPTION
**Pull request by TomFischer**
as titled

### CODE REVIEW

**Comment by chleh** [comment]
So it's quicksort again...
Could you provide a test that only sorts a part of an array, please?

**Comment by TomFischer** [comment]
Christoph you are right. I will write a test.

**Comment by TomFischer** [comment]
Jenkins, test this please.

**Comment by endJunction** [comment]
Looks good!

**Comment by endJunction** [comment]
Jenkins, test this please.

**Comment by endJunction** [comment]
@bilke Could you please have a look on the jenkins' builds https://svn.ufz.de:8443/job/OGS-6/job/Win-PRs/581/ and https://svn.ufz.de:8443/job/OGS-6/job/Linux-PRs/666/ ?
Windows is not starting, Linux cannot find Eigen/Eigen, but builds gui-linux-pr at the same time...

**Comment by bilke** [comment]
- Mac is fine (there was a job in a deadlock)

**Pull request merged**
