### PR TITLE
Fixing namespaces and removing Mat/Vec templates in NumLib/DOF

### PR DESCRIPTION
**Pull request by norihiro-w**
follow up of #1261

- fix that some classes in NumLib/DOF dir have MathLib namespace
- remove Mat/Vec templates in NumLib/DOF (i.e. GlobalMatrix/VectorProvider, Matrix/VectorProvider)

### CODE REVIEW

**Comment by norihiro-w** [comment]
suggest reviewing commit by commit

**Comment by endJunction** [comment]
:+1: 
Like it much better!

I'd suggest to write in the commit messages the actual description of the change. (Like it is suggested in the man page of git-commit, discussion section: "Though not required, it’s a good idea to begin the commit message with a single short (less than 50 character) line summarizing the change, followed by a blank line and then a more thorough description. "

If you are going to reformat some macros or long lines, please do it for the changed lines only, not for whole directories.

**Comment by norihiro-w** [comment]
I'll not format the commits in this PR

**Comment by endJunction** [comment]
@norihiro-w This needs a rebase.

**Comment by endJunction** [comment]
Thanks.
@chleh Would you merge this please?

**Pull request merged**
