### PR TITLE
Jenkins job: No dependencies

### PR DESCRIPTION
**Pull request by bilke**

### CODE REVIEW

**Comment by bilke** [comment]
ctest `MapGeometryToMeshSurface-MapGeometryToMeshSurface_Ammer-time-diff` fails because output file was generated on `envinf1` but test now runs in Docker.

**Comment by endJunction** [comment]
Please rebase to 6.0.7 before merging.

**Comment by endJunction** [comment]
No activity for more than 30 days.

**Comment by endJunction** [comment]
I'll close this one so far. Can be reopened if needed.

**Pull request closed without merging**
