### PR TITLE
Integrate test data with git-lfs into the main source repo

### LINKED ISSUE #1972: Checkout data repository takes long time
checkout submodule still has problem on jenkins as
```
-- Updating submodule Tests/Data

fatal: reference is not a tree: 2738e3e8f958028e4532276638c534c9916fe0b9

Unable to checkout '2738e3e8f958028e4532276638c534c9916fe0b9' in submodule path 'Tests/Data'
```
The checkout works randomly. I have tested that to clone the data repository takes very long time. @bilke : Is it possible that  jenkins refuses to checkout Tests/data due to the time limitation.

### PR DESCRIPTION
**Pull request by bilke**
Follow-up on and closes #1972.

## Usage:

- Use `git lfs clone https://github.com/ufz/ogs` to speed up the download of files (takes around 10s for the test data files on a fast internet connection, equals to around 175 MB at the moment)
    - To speed this up even more you can pass `-I` and `-X` parameters to `git lfs clone` for cloning just specific paths, see the [man page](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-clone.1.ronn)
- Use `git lfs fetch` or `git lfs pull` for updating, `git lfs push` for pushing
- From time to time you may clean-up with `git lfs prune`

## Benefits

- Much faster for downloading
- No hassle with separate PRs for test data
- No more checkout failures because of the current shallow clone behaviour which does not work as we expected
- One system for different types of additional files (test data, web content, example content)
- If you are lazy like me and always forget to type the right thing: `alias gcl='git lfs clone'` or `git config --global alias.clone 'clone lfs'`

## Attention

- You may run into API rate limits of GitHub when cloning a repo with the regular clone command -> use `git lfs clone`
- On upgrading your branches you should not have changed files in Tests/Data -> please clean this directory before updating, merging, rebasing
- There is a storage limit on GitHub on lfs files (I think it is 1 GB per repo), we will hit that at some point -> we can migrate our lfs storage somewhere else, or move entirely to our own Gitlab

## How to migrate from submodule to lfs

We will keep the original submodule in `Tests/Data` for a while. The migrated files can be found in `Tests/lfs-data`. In order to update an existing branch (with modifications to the test data files) follow these steps:

- `git fetch origin && git rebase origin/master`
- `rsync -a Tests/Data/* Tests/lfs-data` and then checking with `git status` if the modified files are the intended ones before committing. Thereby ignore the following :
    - `Tests/lfs-data/FileIO/swmm_input_example.inp` (change should be ignored / discarded)
    - `Tests/lfs-data/Parabolic/ComponentTransport/elder/elder.prj` (change should be ignored / discarded)
    - `Tests/lfs-data/Jenkinsfile` (can be deleted)
    - `Tests/lfs-data/README.md` (can be deleted)
- From now on use `Tests/lfs-data` only!

After a transition period `Tests/Data` submodule will be removed and `Tests/lfs-data` will be renamed to `Tests/Data`.

## TODO (after merge)

- [ ] Deprecate ogs-data repo (leave it as it but put a large warning into the README)
- [ ] Check for wrongly committed files in Jenkins, [see SO question](https://stackoverflow.com/questions/47072267/how-to-check-that-all-git-lfs-tracked-and-committed-files-are-pointers)

### CODE REVIEW

**Comment by endJunction** [comment]
@bilke I started collecting ideas for the migration. Until then this is WIP.

**Comment by bilke** [comment]
@endJunction Prepared [a branch](https://github.com/bilke/ogs/tree/lfs2) for testing the migration (I was somehow not able to rewrite this PRs branch history..). New lfs files are in `Tests/lfs-data`. Can you try rebasing an existing branch? Thanks!

**Comment by endJunction** [comment]
@bilke The 'lfs2' branch looks good! I was able to rebase on top of it w/o problems. What do you suggest for the two tests/data folder synchronization?

**Comment by bilke** [comment]
@endJunction Good! For synchronisation:

Either you know which files to synchronize and simply copy them or running rsync from old to new (e.g. `cd ogs-source-dir && rsync -a Tests/Data/* Tests/lfs-data`) and then checking with `git status` if the modified files are the intended ones before committing. Ignore the following:

- `Tests/lfs-data/Jenkinsfile`
- `Tests/lfs-data/README.md`

**Comment by endJunction** [comment]
If there are no objections to putting tests into git lfs instead of a submodule, this can be merged tonight and the transition begins with all open PRs.

Again, the background for this change is slow checkout of Tests/Data submodule and a not working shallow clone.

**Comment by wenqing** [comment]
:fast_forward:

**Comment by TomFischer** [comment]
⏩

**Comment by endJunction** [comment]
Moved to #1982

**Pull request closed without merging**
