### PR TITLE
[GL] Make tetgen predicates in OGS available.

### PR DESCRIPTION
**Pull request by TomFischer**
The predicates will be used for a robust line segment intersection algorithm. This algorithm will be used in the reimplementation of the surface mapping algorithm, see issue #944.

### CODE REVIEW

**Comment by bilke** [comment]
Until now tetgen is a required submodule for the GUI only. See [SubmoduleSetup.cmake](https://github.com/ufz/ogs/blob/master/scripts/cmake/SubmoduleSetup.cmake#L7-L17), maybe you have to move `ThirdParty/tetgen` to line 12.

**Comment by TomFischer** [comment]
@bilke Thank you for your hint.

**Comment by endJunction** [comment]
Is there a namespace for the predicates, or will they land in global namespace? Or will there be some wrappers in GeoLib?

**Comment by endJunction** [comment]
From discussion with Tom: There predicates will be placed in ExactPredicates namespace. There will be interfaces in GeoLib.

**Pull request merged**
