### PR TITLE
delete unused stuff in BaseLib

### PR DESCRIPTION
**Pull request by norihiro-w**
as titled

### CODE REVIEW

**Comment by chleh** [comment]
:+1:

**Comment by endJunction** [comment]
Somewhere in the cmake scripts the little/big endian things are checked. The cmake config needs an update too.

**Comment by TomFischer** [comment]
Please don't merge. I need some time to check if RangeValidator is used in some of my branches.

**Comment by norihiro-w** [comment]
@endJunction thanks. I deleted it

**Comment by endJunction** [comment]
:fast_forward: from my side.
Waiting for Tom.
@TomFischer  please mark for rebase, or comment when ready.

**Comment by TomFischer** [comment]
:+1:

**Comment by endJunction** [comment]
I'd have rebased this. When running git bisect it is way easier to find something when the history is linear.

**Comment by norihiro-w** [comment]
I don't agree with the reason. Allowing non-linear history (branching-merging ) is a heart of git, isn't it? Why should we give up following it because of a particular poor algorithm? Besides, keeping linear history is not realistic because a branch itself an be made of several PRs and have nonlinear history.

**Pull request merged**
