### PR TITLE
[web] Marketing / features index page

### PR DESCRIPTION
**Pull request by bilke**
In preparation of the shutdown of the existing opengeosys.org page and as a todo from the usability initiative here is the first draft of a features-at-a-glance index page.

[Check the page here!](https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-2123/lastSuccessfulBuild/Web/)

Now I need your help: Please contribute feature descriptions and fancy images from your point of view! A few ideas:

- Implemented processes worth mentioning, all @ufz/members 
- Interfaces to other data formats / applications
- HPC and parallelization, @wenqing @TomFischer 
- pre-, post-processing, Data Explorer, @TomFischer @rinkk and me
- Visualization, @rinkk and me
- Python bindings? @chleh 
- Applications / projects, all
- QA, benchmarking, me?
- ... (more ideas from you)
- [x] Coupling schemes, @endJunction @wenqing 
- [x] Software engineering, me
- [x] Impressum

Feel free to directly add to this PR! The pages content is at `web/content/_index.pandoc`. Or you can also post your description here as a comment and I will integrate it.

This PR should be finished on 1st of July latest.

### CODE REVIEW

**Comment by wenqing** [comment]
@endJunction Any comment?
**Coupling Scheme**

A coupled system of  equations can be either solved in a fully coupled way of the monolithic method, or in the sequential manner of the staggered scheme (as shown in the following figure).
staggered
In current ogs6, the monolithic scheme is applied for all coupled processes, while the staggered scheme are available for the coupled processes of themo-hydraulic, thermo-mechanical, and phase field mechanical problems.
  
@bilke I posted two descriptions as comment.

**Comment by TomFischer** [comment]
@wenqing , @bilke 
I could create some figures from the fractured cube. I have alreade run time figures and scaling curves for different architectures (EVE, mistral, TAURUS and JURECA). But I believe this is nothing for the start page of the website.

**Comment by chleh** [comment]
I just started working on some BCs based on Python. Once that's finished I can add some bullet points about it.

**Comment by bilke** [comment]
@ufz/members 

Is now online at www.opengeosys.org.

Old adresses such as [docs.opengeosys.org](http://docs.opengeosys.org) and [benchmarks.opengeosys.org](http://benchmarks.opengeosys.org) should redirect accordingly.

**Pull request merged**
