### PR TITLE
[CMake] Fixed submodule init / update on Windows

### PR DESCRIPTION
**Pull request by bilke**
Submodule init / update checks are now platform-independent. This should speed up Windows CMake configure time a little bit.

### CODE REVIEW

**Comment by endJunction** [comment]
It looks less platform-dependent :fast_forward: 
Though I didn't check the behaviour...

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by bilke** [comment]
Jenkins test this please.

**Comment by TomFischer** [comment]
Works for me. :+1:

**Pull request merged**
