### PR TITLE
Removed using namespace GeoLib.

### PR DESCRIPTION
**Pull request by bilke**
Should fix windows builds on Jenkins.

### CODE REVIEW

**Comment by TomFischer** [comment]
:+1:

What was the problem with the code before?

**Comment by bilke** [comment]
I do not know what was the reason (maybe an updated CMake) but since yesterday the Jenkins Windows build includes more Windows default directories where some more non-namespaced classes (i.e. `Polygon` in `wingdi.h`) get included (see current Jenkins Windows builds). This fixes it.

**Comment by TomFischer** [comment]
Thanks for explanation. So the lesson is to structure our sources into namespaces **and** avoid the keyword `using` even in cpp files?!

**Comment by bilke** [comment]
I don't really know.. Maybe I can also check how these windows headers get included, because a developer should not care about things which are not related.. but also because the `GeoLib::` namespace prefix was sometimes used and sometimes not I made those changes.

**Comment by bilke** [comment]
retest this please

**Comment by endJunction** [comment]
@TomFischer Actually those who put something into global namespace break other's code.
Using `using namespace X` is perfectly correct (and in my opinion desirable, because of less code) in cpp files; not in header files.

When green, :fast_forward:

**Comment by endJunction** [comment]
Jenkins, test this please.

**Comment by endJunction** [comment]
It's green :), thanks Lars!

@norihiro-w Would you please rebase all your PRs on new ufz/master; the PRs will be tested on Windows too then. (A merge of the ufz/master into the PR is also OK, but less clean.)

**Comment by norihiro-w** [comment]
@endJunction rebased

**Pull request merged**
