### PR TITLE
Changed directory name of MaterialsLib to MaterialLib

### PR DESCRIPTION
**Pull request by wenqing**
As discussed with Christoph, I changed the name of the directory for material to merge my stuff.

### CODE REVIEW

**Comment by wenqing** [comment]
@chleh If you think it causes too much changes in your current implementation, I can discard this PR.

**Comment by chleh** [comment]
:fast_forward: 
It's OK for me. Any problems will be resolvable with search and replace.

**Comment by endJunction** [comment]
No objections either.
Can be merged after rebase...

**Comment by wenqing** [comment]
rebased.

**Pull request merged**
