### PR TITLE
Cleanup in GeoLib

### PR DESCRIPTION
**Pull request by TomFischer**
PR contains:
- Removal of unused code.
- Change how intersection points are inserted in the GMSHPolygonTree (commit 6d3685e - the only commit with some "real" changes)
- Substitutions of `size_t` with `std::size_t` and `NULL` -> `nullptr`.

### CODE REVIEW

**Comment by endJunction** [comment]
Very nice! :+1:

**Comment by bilke** [comment]
:+1:

**Comment by endJunction** [comment]
The last message from the jenkins says there is some error but because jenkins died I cannot check it (and can not merge).
@bilke Can you look into the jenkins' problems please?

**Comment by bilke** [comment]
Our IT-department died as well...

**Comment by TomFischer** [comment]
Jenkis, please test this.

**Comment by TomFischer** [comment]
Jenkins, please test this.

**Comment by TomFischer** [comment]
Test this please, Jenkins.

**Comment by endJunction** [comment]
The jenkins' error is not related to the GeoLib but is linking of libGL what is failing (on envinf1 due to some updates).

**Pull request merged**
