### PR TITLE
activates tests on travis also for GUI builds

### PR DESCRIPTION
**Pull request by norihiro-w**
related to #1397, currently some tests using Qt are not executed on travis, because only GUI builds include Qt and tests are deactivated for those builds. This PR activates the tests.

### CODE REVIEW

**Comment by norihiro-w** [comment]
of course, this makes travis jobs longer

**Comment by norihiro-w** [comment]
it seems GUI builds on Jenkins are executing tests. if Jenkins test is enough, I would close this PR.

**Comment by bilke** [comment]
Job run times on Travis vary a lot. Sometime non-gui jobs even take as long as over 15 mins, so feel free to merge this.

**Comment by endJunction** [comment]
So long the jobs are not aborted too often on travis because of the time limit, it's good to include more tests. We'll see.

**Pull request merged**
