### PR TITLE
[web] Remaining benchmarks

### PR DESCRIPTION
**Pull request by bilke**
Migrated all benchmarks from docs.opengeosys.org.
Once merged I will redirect from docs.opengeosys.org to this.

To discuss: where to store additional files, e.g. pdfs, in the future.

### CODE REVIEW

**Comment by endJunction** [comment]
pdf's, graphics, scripts to produce the graphics, *etc.* also in the web/content folder.

**Comment by endJunction** [comment]
In a fresh ogs checkout, running `npm install` in web/ yields some warnings (maybe not important at all):
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN opengeosys.org@0.0.1 license should be a valid SPDX license expression
```

Then `npm run build` looks good, but debugging the site (*e.g.* F12 in chromium) shows errors like this for most of the benchmark sites:
```
GET http://localhost:1313/vis/Elliptic/square_1x1_GroundWaterFlow/square_1e2_neumann_pcs_0_ts_1_t_1.000000.vtu/index.json 404 (Not Found)
Uncaught (in promise) 
XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "http://localhost:1313/vis/Elliptic/square_1x1_Grou…_1e2_neumann_pcs_0_ts_1_t_1.000000.vtu/index.json"…}
```
.... and there is no webGL image...

**Comment by endJunction** [comment]
In `Lubby2; Creep example` the images are shown as icons only. The actual images in `public/.../lubby2.png` is an ascii with git-lfs description. So somehow these are not checked out properly.

**Comment by bilke** [comment]
@endJunction 

- benchmark vis are created by running the corresponding benchmark; as part of the benchmark tester the output is converted which is then copied to `web/static/vis`; the `static`-folder is then picked up by hugo and copied over to the `public`-folder; **TLDR:** `make web` takes care of everything...
- maybe you haven't installed git-lfs? [The Jenkins-generated site](https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-1723/Web/) is fine.

**Comment by endJunction** [comment]
@bilke 
git-lfs/2.0-pre (GitHub; linux amd64; go 1.7.5)
`make web` requires access token (content) and is not running...

**Comment by endJunction** [comment]
@bilke `make web` is kind of running, but I still don't see the vtk js openGL things, but there is a reason for the WIP ;)
```
➜  r make web
yarn install v0.20.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.61s.
Built target web-install

> opengeosys.org@0.0.1 build /home/naumov/w/ogs/s/web
> gulp build && hugo

[17:15:58] Using gulpfile ~/w/ogs/s/web/gulpfile.js
[17:15:58] Starting 'scss'...
[17:15:58] -> Compiling scss: ./static/css/main.scss
[17:15:58] Starting 'webpack'...
[17:15:59] main.css 23.4 kB (gzipped)
[17:15:59] normalize.css 2.24 kB (gzipped)
[17:15:59] flexboxgrid.min.css 1.86 kB (gzipped)
[17:15:59] all files 27.5 kB (gzipped)
[17:16:01] Finished 'scss' after 3.92 s
[17:16:05] Version: webpack 1.14.0
    Asset    Size  Chunks             Chunk Names
bundle.js  1.6 MB       0  [emitted]  main
[17:16:05] Finished 'webpack' after 7 s
[17:16:05] Starting 'build'...
[17:16:05] Finished 'build' after 31 μs
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
21 regular pages created
3 other pages created
30 non-page files copied
0 paginator pages created
0 news created
total in 525 ms
Built target web
```
I'm off for few days...

**Comment by bilke** [comment]
Sorry you are correct. The `web`-target does not run the benchmarks. So to get everything you have to do `make ctest; make web`.

**Pull request merged**
