### PR TITLE
Test file name check

### PR DESCRIPTION
**Pull request by endJunction**
TEST ONLY. Don't merge.

### CODE REVIEW

**Comment by endJunction** [comment]
@bilke I think the command line becomes too long at some point.

I tested some permutations of the commits and the first three commits in any order (few variations were tried out, not all) are OK, adding one more on top leads to failure.
If my suspicion is correct, adding more files (maybe with long names) will cause the problem too. Let's try!

**Comment by endJunction** [comment]
Nope. That wasn't it. added almost 7k chars worth of new file names. In the original PR there are only around 2k.

**Comment by endJunction** [comment]
I've no further ideas so far. Feel free to reopen, as needed.

**Comment by wenqing** [comment]
@endJunction Thanks a lot for your efforts!

**Comment by bilke** [comment]
@endJunction Thanks Dima for testing!

**Pull request closed without merging**
