### PR TITLE
Wrote some more docu

### PR DESCRIPTION
**Pull request by chleh**
Follow-up of #1370.

I also noticed that our LIS default options are erroneous.

Contains docu for
* linear solvers
* nonlinear solvers
* ODE solver

### CODE REVIEW

**Comment by TomFischer** [comment]
Seems that this PR contains also the first part of the docu (PR #1370 ). Maybe it is better to separate the PRs?

**Comment by chleh** [comment]
OK, next time I won't do follow-ups. This time please either wait for this PR to be rebased after the first one is merged, or only review the commits after @endJunction's.

**Comment by chleh** [comment]
What's the problem here?
https://svn.ufz.de:8443/job/OGS-6/job/ufz/job/PR-1373/10/console

**Comment by endJunction** [comment]
:fast_forward:

**Comment by endJunction** [comment]
Not so much interest in documentation there is, isn't it?

**Pull request merged**
